CREATE TABLE IF NOT EXISTS bills (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'Owner user id',
    account_date DATE NOT NULL COMMENT 'Accounting date',
    category_id BIGINT UNSIGNED NOT NULL COMMENT 'Config item id',
    category_name VARCHAR(128) NOT NULL COMMENT 'Cached category display name',
    bill_type VARCHAR(32) NOT NULL COMMENT 'income expense refund or investment action',
    payment_method VARCHAR(32) NOT NULL COMMENT 'cash credit_card installment presale',
    is_fixed_asset TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether this bill is for fixed asset',
    amount DECIMAL(18,2) NOT NULL COMMENT 'Bill amount',
    tags JSON NULL COMMENT 'Bill tags json array',
    remark VARCHAR(255) NULL COMMENT 'Remark',
    transfer_group_id VARCHAR(64) NULL COMMENT 'Transfer pair group id',
    transfer_target_type VARCHAR(32) NULL COMMENT 'system_user or other_person',
    transfer_target_user_id BIGINT UNSIGNED NULL COMMENT 'Target user id for transfer',
    credit_card_id BIGINT UNSIGNED NULL COMMENT 'Related credit card id',
    is_installment TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether this bill is installment',
    installment_months INT UNSIGNED NULL COMMENT 'Installment months',
    investment_action VARCHAR(32) NULL COMMENT 'open add reduce dividend',
    related_investment_id BIGINT UNSIGNED NULL COMMENT 'Reserved investment id',
    product_code VARCHAR(64) NULL COMMENT 'Reserved product code',
    product_name VARCHAR(128) NULL COMMENT 'Reserved product name',
    organization_name VARCHAR(128) NULL COMMENT 'Reserved organization name',
    share_amount DECIMAL(18,6) NULL COMMENT 'Reserved share amount',
    related_asset_id BIGINT UNSIGNED NULL COMMENT 'Reserved fixed asset id',
    special_status VARCHAR(32) NOT NULL DEFAULT 'none' COMMENT 'special handling status',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    deleted_at DATETIME NULL COMMENT 'Soft delete time',
    KEY idx_bills_user_date_category (user_id, account_date, category_id),
    KEY idx_bills_transfer_group (transfer_group_id),
    KEY idx_bills_credit_card (credit_card_id)
) COMMENT='Accounting bills';
