use chrono::{NaiveDate, NaiveDateTime};
use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct Bill {
    pub id: u64,
    pub user_id: u64,
    pub account_date: NaiveDate,
    pub category_id: u64,
    pub category_name: String,
    pub bill_type: String,
    pub payment_method: String,
    pub is_fixed_asset: bool,
    pub amount: String,
    pub tags: Vec<String>,
    pub remark: Option<String>,
    pub transfer_group_id: Option<String>,
    pub transfer_target_type: Option<String>,
    pub transfer_target_user_id: Option<u64>,
    pub transfer_target_user_name: Option<String>,
    pub credit_card_id: Option<u64>,
    pub credit_card_name: Option<String>,
    pub is_installment: bool,
    pub installment_months: Option<u32>,
    pub investment_action: Option<String>,
    pub related_investment_id: Option<u64>,
    pub related_investment_name: Option<String>,
    pub product_code: Option<String>,
    pub product_name: Option<String>,
    pub organization_name: Option<String>,
    pub share_amount: Option<String>,
    pub related_asset_id: Option<u64>,
    pub related_asset_name: Option<String>,
    pub related_debt_id: Option<u64>,
    pub special_status: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}
